export const SITE = {
  url: "https://mohamedkhaled-law.com",
  nameEn: "Dr. Mohamed Khaled Mekky — Law Firm",
  nameAr: "مكتب الدكتور محمد خالد مكي للمحاماة",
  shortEn: "Mohamed Khaled",
  shortAr: "محمد خالد",
  facebook: "https://www.facebook.com/profile.php?id=61559229443838",
  phones: {
    egypt: "01515323936",
    egyptIntl: "+201515323936",
    saudi: "0555518556",
    saudiIntl: "+966555518556",
  },
  whatsapp: "+201515323936",
  locations: [
    {
      id: "sohag",
      cityEn: "Sohag",
      cityAr: "سوهاج",
      countryEn: "Egypt",
      countryAr: "مصر",
      addressEn: "46 El-Galaa St. (Al-Qa'at St.), next to Shady Pharmacy, Sohag",
      addressAr: "٤٦ ش الجلاء (شارع القاعات) بجوار صيدلية شادي، سوهاج",
      phone: "+201515323936",
      geo: { lat: 26.5594, lng: 31.6948 },
    },
    {
      id: "maragha",
      cityEn: "El Maragha",
      cityAr: "المراغة",
      countryEn: "Egypt",
      countryAr: "مصر",
      addressEn: "Sohag — El Maragha — Old Maragha Court St.",
      addressAr: "سوهاج - المراغة - شارع المحكمة المراغة القديمة",
      phone: "+201515323936",
      geo: { lat: 26.6906, lng: 31.5814 },
    },
    {
      id: "mecca",
      cityEn: "Mecca",
      cityAr: "مكة المكرمة",
      countryEn: "Saudi Arabia",
      countryAr: "المملكة العربية السعودية",
      addressEn: "Mecca — Third Ring Road — Blue Building — 3rd Floor",
      addressAr: "مكة المكرمة - طريق الدائري الثالث - العمارة الزرقاء - الدور الثالث",
      phone: "+966555518556",
      geo: { lat: 21.4306394, lng: 39.7788357 },
    },
  ],
} as const;

export type Locale = "ar" | "en";
