/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangAppRouteImport } from './routes/$lang._app'
import { Route as LangPublicRouteImport } from './routes/$lang._public'
import { Route as LangAppDashboardRouteImport } from './routes/$lang._app.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAppRoute = LangAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => LangRoute,
} as any)
const LangPublicRoute = LangPublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => LangRoute,
} as any)
const LangAppDashboardRoute = LangAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LangAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/dashboard': typeof LangAppDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/dashboard': typeof LangAppDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/_app': typeof LangAppRouteWithChildren
  '/$lang/_public': typeof LangPublicRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/_app/dashboard': typeof LangAppDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$lang' | '/$lang/' | '/$lang/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$lang' | '/$lang/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/_app'
    | '/$lang/_public'
    | '/$lang/'
    | '/$lang/_app/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_app': {
      id: '/$lang/_app'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAppRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_public': {
      id: '/$lang/_public'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangPublicRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_app/dashboard': {
      id: '/$lang/_app/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangAppDashboardRouteImport
      parentRoute: typeof LangAppRoute
    }
  }
}

interface LangAppRouteChildren {
  LangAppDashboardRoute: typeof LangAppDashboardRoute
}

const LangAppRouteChildren: LangAppRouteChildren = {
  LangAppDashboardRoute: LangAppDashboardRoute,
}

const LangAppRouteWithChildren =
  LangAppRoute._addFileChildren(LangAppRouteChildren)

interface LangRouteChildren {
  LangAppRoute: typeof LangAppRouteWithChildren
  LangPublicRoute: typeof LangPublicRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAppRoute: LangAppRouteWithChildren,
  LangPublicRoute: LangPublicRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
